### ISSUE TITLE
Bot errors

### ISSUE THREAD

**Issue by ngc92** [danielknobe/blobbyvolley2#106]
Some bots currently cause lua to emit errors. Examples are:
* [x] - `[string "scripts/Union.lua"]:275: attempt to compare nil with number` 
* [x] - `[string "scripts/Union.lua"]:275: attempt to compare nil with number`
* [x] - `[string "scripts/Union3.lua"]:452: attempt to compare nil with number`
* [x] - `[string "scripts/hyp014.lua"]:456: attempt to compare number with nil`
* [x] - `[string "scripts/hyp014.lua"]:307: attempt to perform arithmetic on a nil value (global 't2')`
* [x] - `[string "scripts/Union3.lua"]:466: attempt to compare nil with number`
* [x] - `[string "scripts/Union3.lua"]:114: attempt to index a nil value (local 'best_fun')`

**Comment by ngc92** [comment]
The hyp014 problems should be fixed with now that #109 is merged.

**Comment by danielknobe** [comment]
The Union3 problem is fixed with #117 .

**Comment by danielknobe** [comment]
Are all errors fixed?

**Comment by ngc92** [comment]
I ran the bot benchmarks again, and I'm still getting a `nil` error from `Union3`, but from a different line.
Currently, the results look like this:

## Scores:
|                |   hyp014.lua |   gintonicV9.lua |   reduced.lua |   com_11.lua |   Union.lua |   axji-0-2.lua |   Union3.lua |
|:---------------|-------------:|-----------------:|--------------:|-------------:|------------:|---------------:|-------------:|
| hyp014.lua     |           15 |                3 |             1 |            4 |          10 |             15 |           11 |
| gintonicV9.lua |           15 |                6 |             7 |           15 |           4 |             15 |           15 |
| reduced.lua    |           15 |               15 |            15 |           15 |           7 |             15 |           15 |
| com_11.lua     |           15 |                4 |             0 |           23 |           8 |             15 |           10 |
| Union.lua      |           15 |               15 |            15 |           15 |          13 |             15 |           12 |
| axji-0-2.lua   |            0 |                0 |             0 |            0 |           0 |           3513 |            0 |
| Union3.lua     |           15 |               17 |             0 |           15 |          15 |             15 |           15 |

## Durations:
|                |   hyp014.lua |   gintonicV9.lua |   reduced.lua |   com_11.lua |   Union.lua |   axji-0-2.lua |   Union3.lua |
|:---------------|-------------:|-----------------:|--------------:|-------------:|------------:|---------------:|-------------:|
| hyp014.lua     |         1424 |                0 |             0 |            0 |           0 |              0 |            0 |
| gintonicV9.lua |          831 |             4499 |             0 |            0 |           0 |              0 |            0 |
| reduced.lua    |          850 |             8438 |         10349 |            0 |           0 |              0 |            0 |
| com_11.lua     |         1025 |             3856 |          3131 |         5483 |           0 |              0 |            0 |
| Union.lua      |         4327 |             3000 |          2337 |         4147 |       10101 |              0 |            0 |
| axji-0-2.lua   |          105 |               95 |            42 |           56 |          80 |          43200 |            0 |
| Union3.lua     |         1780 |             3682 |          1636 |         5129 |        7329 |            133 |          710 |

so axji is really bad, I think the others look generally decent enough.

**Comment by danielknobe** [comment]
Axji seems to be as strong as in 1.0 release. #124 fixes compare nil error. With the branch fix/union3_time_to_blob I can't reproduce the last open task (index a nil value) in this issue.

I think if you set the bot difficulty to easy, the bots should be even weaker. What do you think?

**Comment by ngc92** [comment]
I generally agree, but I want to be careful so that they don't appear too much deliberately stupid. I think even on easiest difficulty, a completely new player shouldn't actually win -- but they should be able to get some points, so it doesn't seem like an insurmountable challenge.

One thing is that the bot difficulty currently resets (i.e., the bot gets stronger) after every point -- we could change this to only happen every time the player scores, I think. Or at least, only reset partially when the bot scores.

**Comment by danielknobe** [comment]
Union3 warnings fixed with #124 . We can close this issue.
